export const ActionTypes = {
    NEXT_PRODUCT: "NEXT_PRODUCT",
    NEXT_PRODUCT_ASYNC: "NEXT_PRODUCT_ASYNC",
    PREV_PRODUCT: "PREV_PRODUCT",
    PREV_PRODUCT_ASYNC: "PREV_PRODUCT_ASYNC",
    SEARCH_PRODUCT: "SEARCH_PRODUCT",
    SEARCH_PRODUCT_SUCCESS: "SEARCH_PRODUCT_SUCCESS",
    SEARCH_PRODUCT_FAILURE: "SEARCH_PRODUCT_FAILURE",
}